export const UPDATE_NOTIFICATION = "UPDATE_NOTIFICATION";

export const CREATE_POST = "CREATE_POST";
export const CREATE_POST_ERROR = "CREATE_POST_ERROR";
export const IS_POST_CREATE_LOADING = "IS_POST_CREATE_LOADING";
export const FETCH_ALL_POSTS = "FETCH_ALL_POSTS";
export const IS_ALL_POSTS_LOADING = "IS_ALL_POSTS_LOADING";
export const FETCH_ALL_POSTS_ERROR = "FETCH_ALL_POSTS_ERROR";
export const IS_SPECIFIC_POST_LOADING = "IS_SPECIFIC_POST_LOADING";
export const FETCH_SPECIFIC_POSTS = "FETCH_SPECIFIC_POSTS"; 
export const FETCH_SPECIFIC_POST_ERROR = "FETCH_SPECIFIC_POST_ERROR";