export const UPDATE_NOTIFICATION = "UPDATE_NOTIFICATION";

export const CREATE_POST = "CREATE_POST";
export const CREATE_POST_ERROR = "CREATE_POST_ERROR";
export const IS_POST_CREATE_LOADING = "IS_POST_CREATE_LOADING";
export const FETCH_ALL_POSTS = "FETCH_ALL_POSTS";