export const UPDATE_NOTIFICATION = "UPDATE_NOTIFICATION";

export const CREATE_POST = "CREATE_POST";
export const CREATE_POST_ERROR = "CREATE_POST_ERROR";
export const IS_POST_CREATE_LOADING = "IS_POST_CREATE_LOADING";
export const FETCH_ALL_POSTS = "FETCH_ALL_POSTS";
export const IS_ALL_POSTS_LOADING = "IS_ALL_POSTS_LOADING";
export const FETCH_ALL_POSTS_ERROR = "FETCH_ALL_POSTS_ERROR";
export const IS_SPECIFIC_POST_LOADING = "IS_SPECIFIC_POST_LOADING";
export const FETCH_SPECIFIC_POSTS = "FETCH_SPECIFIC_POSTS"; 
export const FETCH_SPECIFIC_POST_ERROR = "FETCH_SPECIFIC_POST_ERROR";

export const REGISTER_LOADING = "REGISTER_LOADING";
export const CREATE_USER = "CREATE_USER";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const IS_AUTH_LOADING = "IS_AUTH_LOADING";
export const AUTH_ERROR = "AUTH_ERROR";
export const SIGN_IN = "SIGN_IN";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

export const SET_USER_PROFILE = "SET_USER";
export const LOADING_USER_PROFILE = "LOADING_USER_PROFILE";
export const SET_PROFILE_IMAGE = "SET_PROFILE_IMAGE";
export const LOADING_PROFILE_IMAGE = "LOADING_PROFILE_IMAGE";
export const SET_USER_DETAILS = "SET_USER_DETAILS";
export const LOADING_USER_DETAILS = "LOADING_USER_DETAILS";
